//
//  Recipe.swift
//  Chef Book
//
//  Created by David Grunsted on 6/21/24.
//

import Foundation
import SwiftData

struct RecipeNote: Identifiable, Decodable, Hashable {
    let id: String
    var content: String
}

//@Model
struct Recipe: Identifiable, Decodable, Hashable, Equatable {
    func hash(into hasher: inout Hasher) { hasher.combine(id) }
    let id: String
    var title: String
    var desc: String
    var link_to_original_web_page: String
    var author: String
    var time_in_seconds: Int
    var time_display: String
    var directions: [String]
    var image: String
    var servings: String
    var cuisine: String
    var country: String
    var notes: [RecipeNote]
    var ingredients: [Ingredient]
    var category: String
    var made: Bool
    var favorite: Bool
    var url_id: String
    var ingredientCount: Int
    var directionCount: Int
    var user: String
    var isDetailLoaded: Bool

    init(id: String, title: String, description: String, link_to_original_web_page: String, author: String, time_in_seconds: Int, time_display: String = "", directions: [String], image: String, servings: String, cuisine: String, country: String, notes: [RecipeNote], ingredients: [Ingredient], category: String, made: Bool, favorite: Bool, url_id: String = "", ingredientCount: Int? = nil, directionCount: Int? = nil, user: String = "", isDetailLoaded: Bool = true) {
        self.id = id
        self.title = title
        self.desc = description
        self.link_to_original_web_page = link_to_original_web_page
        self.author = author
        self.time_in_seconds = time_in_seconds
        self.time_display = time_display
        self.directions = directions
        self.image = image
        self.servings = servings
        self.cuisine = cuisine
        self.country = country
        self.notes = notes
        self.ingredients = ingredients
        self.category = category
        self.made = made
        self.favorite = favorite
        self.url_id = url_id
        self.ingredientCount = ingredientCount ?? ingredients.count
        self.directionCount = directionCount ?? directions.count
        self.user = user
        self.isDetailLoaded = isDetailLoaded
    }
}

extension Recipe {
    static var display_time: String {
        "2 hrs"
    }
}


extension Recipe {
    static let sampleData: [Recipe] =
    [
        Recipe(id: "12", title: "Lemon  Chicken Piccata 1",
               description: "",
               link_to_original_web_page: "https://damndelicious.net/2016/02/26/easy-lemon-chicken-piccata/",
               author: "David Grunsted",
               time_in_seconds: 1800,
               directions: ["In a large pot of boiling salted water, cook pasta according to package instructions; drain well.",
                            "Season chicken with salt and pepper, to taste.",
                            "Working one at a time, dredge chicken in flour.",
                            "Melt 2 tablespoons butter in a large skillet over medium high heat. Add chicken and cook, flipping once, until cooked through, about 4-5 minutes on each side. Set aside and keep warm.",
                            "Melt remaining 2 tablespoons butter in the skillet. Add garlic and shallots, and cook, stirring frequently, until fragrant, about 2 minutes.",
                            "Stir in chicken broth, wine and lemon juice. Cook, stirring occasionally, until slightly reduced, about 5 minutes.",
                            "Gradually whisk in heavy cream until slightly thickened, about 3-4 minutes",
                            "season with salt and pepper, to taste. Stir in capers."],
               image: "https://s23209.pcdn.co/wp-content/uploads/2016/02/Easy-Lemon-Chicken-Piccata220602_DD_Easy-Lem-Chx-Piccata_397-1365x2048.jpg",
               servings: "4",
               cuisine: "Mediteranean",
               country: "France",
               notes: [RecipeNote(id: "sample1", content: "remove chicken before it falls apart and chop up to add back at the end"), RecipeNote(id: "sample2", content: "cook down sauce before adding the potatoes")],
               ingredients: [Ingredient(id: "1", quantity: 1, unit: "pound", name: "Spaghetti"),
                             Ingredient(id: "1", quantity: 1, unit: "pound", name: "boneless skinless chicken breasts, cut crosswise in half"),
                             Ingredient(id: "1", quantity: 0, unit: "", name: "Kosher salt and freshly ground black pepper, to taste"),
                             Ingredient(id: "1", quantity: 0.5, unit: "cup", name: "all-purpose flour"),
                             Ingredient(id: "1", quantity: 4, unit: "tablespoon", name: "unsalted butter, divided"),
                             Ingredient(id: "1", quantity: 2, unit: "clove", name: "garlic, minced"),
                             Ingredient(id: "1", quantity: 0.25, unit: "cup", name: "diced shallots"),
                             Ingredient(id: "1", quantity: 0.75, unit: "cup", name: "chicken broth"),
                             Ingredient(id: "1", quantity: 0.25, unit: "cup", name: "dry white wine"),
                             Ingredient(id: "1", quantity: 0, unit: "", name: "Juice of 1 lemon"),
                             Ingredient(id: "1", quantity: 0.5, unit: "cup", name: "heavy cream"),
                             Ingredient(id: "1", quantity: 0.25, unit: "cup", name: "capers, drained"),
                             Ingredient(id: "1", quantity: 2, unit: "tablespoon", name: "chopped fresh parsley leaves")],
               category: "Pasta",
               made: true,
               favorite: false),
        Recipe(id: "11", title: "Lemon  Chicken Piccata 2",
               description: "",
               link_to_original_web_page: "https://damndelicious.net/2016/02/26/easy-lemon-chicken-piccata/",
               author: "",
               time_in_seconds: 1800,
               directions: ["In a large pot of boiling salted water, cook pasta according to package instructions; drain well.",
                            "Season chicken with salt and pepper, to taste.",
                            "Working one at a time, dredge chicken in flour.",
                            "Melt 2 tablespoons butter in a large skillet over medium high heat. Add chicken and cook, flipping once, until cooked through, about 4-5 minutes on each side. Set aside and keep warm.",
                            "Melt remaining 2 tablespoons butter in the skillet. Add garlic and shallots, and cook, stirring frequently, until fragrant, about 2 minutes.",
                            "Stir in chicken broth, wine and lemon juice. Cook, stirring occasionally, until slightly reduced, about 5 minutes.",
                            "Gradually whisk in heavy cream until slightly thickened, about 3-4 minutes",
                            "season with salt and pepper, to taste. Stir in capers."],
               image: "https://s23209.pcdn.co/wp-content/uploads/2016/02/Easy-Lemon-Chicken-Piccata220602_DD_Easy-Lem-Chx-Piccata_397-1365x2048.jpg",
               servings: "4",
               cuisine: "Mediteranean",
               country: "France",
               notes: [],
               ingredients: [Ingredient(id: "1", quantity: 1, unit: "pound", name: "Spaghetti"),
                             Ingredient(id: "1", quantity: 1, unit: "pound", name: "boneless skinless chicken breasts, cut crosswise in half"),
                             Ingredient(id: "1", quantity: 0, unit: "", name: "Kosher salt and freshly ground black pepper, to taste"),
                             Ingredient(id: "1", quantity: 0.5, unit: "cup", name: "all-purpose flour"),
                             Ingredient(id: "1", quantity: 4, unit: "tablespoon", name: "unsalted butter, divided"),
                             Ingredient(id: "1", quantity: 2, unit: "clove", name: "garlic, minced"),
                             Ingredient(id: "1", quantity: 0.25, unit: "cup", name: "diced shallots"),
                             Ingredient(id: "1", quantity: 0.75, unit: "cup", name: "chicken broth"),
                             Ingredient(id: "1", quantity: 0.25, unit: "cup", name: "dry white wine"),
                             Ingredient(id: "1", quantity: 0, unit: "", name: "Juice of 1 lemon"),
                             Ingredient(id: "1", quantity: 0.5, unit: "cup", name: "heavy cream"),
                             Ingredient(id: "1", quantity: 0.25, unit: "cup", name: "capers, drained"),
                             Ingredient(id: "1", quantity: 2, unit: "tablespoon", name: "chopped fresh parsley leaves")],
               category: "Pasta",
               made: true,
               favorite: false),
        Recipe(id: "10", title: "Lemon  Chicken Piccata 3",
               description: "",
               link_to_original_web_page: "https://damndelicious.net/2016/02/26/easy-lemon-chicken-piccata/",
               author: "",
               time_in_seconds: 1800,
               directions: ["In a large pot of boiling salted water, cook pasta according to package instructions; drain well.",
                            "Season chicken with salt and pepper, to taste.",
                            "Working one at a time, dredge chicken in flour.",
                            "Melt 2 tablespoons butter in a large skillet over medium high heat. Add chicken and cook, flipping once, until cooked through, about 4-5 minutes on each side. Set aside and keep warm.",
                            "Melt remaining 2 tablespoons butter in the skillet. Add garlic and shallots, and cook, stirring frequently, until fragrant, about 2 minutes.",
                            "Stir in chicken broth, wine and lemon juice. Cook, stirring occasionally, until slightly reduced, about 5 minutes.",
                            "Gradually whisk in heavy cream until slightly thickened, about 3-4 minutes",
                            "season with salt and pepper, to taste. Stir in capers."],
               image: "https://s23209.pcdn.co/wp-content/uploads/2016/02/Easy-Lemon-Chicken-Piccata220602_DD_Easy-Lem-Chx-Piccata_397-1365x2048.jpg",
               servings: "4",
               cuisine: "Mediteranean",
               country: "France",
               notes: [],
               ingredients: [Ingredient(id: "1", quantity: 1, unit: "pound", name: "Spaghetti"),
                             Ingredient(id: "1", quantity: 1, unit: "pound", name: "boneless skinless chicken breasts, cut crosswise in half"),
                             Ingredient(id: "1", quantity: 0, unit: "", name: "Kosher salt and freshly ground black pepper, to taste"),
                             Ingredient(id: "1", quantity: 0.5, unit: "cup", name: "all-purpose flour"),
                             Ingredient(id: "1", quantity: 4, unit: "tablespoon", name: "unsalted butter, divided"),
                             Ingredient(id: "1", quantity: 2, unit: "clove", name: "garlic, minced"),
                             Ingredient(id: "1", quantity: 0.25, unit: "cup", name: "diced shallots"),
                             Ingredient(id: "1", quantity: 0.75, unit: "cup", name: "chicken broth"),
                             Ingredient(id: "1", quantity: 0.25, unit: "cup", name: "dry white wine"),
                             Ingredient(id: "1", quantity: 0, unit: "", name: "Juice of 1 lemon"),
                             Ingredient(id: "1", quantity: 0.5, unit: "cup", name: "heavy cream"),
                             Ingredient(id: "1", quantity: 0.25, unit: "cup", name: "capers, drained"),
                             Ingredient(id: "1", quantity: 2, unit: "tablespoon", name: "chopped fresh parsley leaves")],
               category: "Pasta",
               made: true,
               favorite: false),
        Recipe(id: "9", title: "Lemon  Chicken Piccata 1",
               description: "",
               link_to_original_web_page: "https://damndelicious.net/2016/02/26/easy-lemon-chicken-piccata/",
               author: "",
               time_in_seconds: 1800,
               directions: ["In a large pot of boiling salted water, cook pasta according to package instructions; drain well.",
                            "Season chicken with salt and pepper, to taste.",
                            "Working one at a time, dredge chicken in flour.",
                            "Melt 2 tablespoons butter in a large skillet over medium high heat. Add chicken and cook, flipping once, until cooked through, about 4-5 minutes on each side. Set aside and keep warm.",
                            "Melt remaining 2 tablespoons butter in the skillet. Add garlic and shallots, and cook, stirring frequently, until fragrant, about 2 minutes.",
                            "Stir in chicken broth, wine and lemon juice. Cook, stirring occasionally, until slightly reduced, about 5 minutes.",
                            "Gradually whisk in heavy cream until slightly thickened, about 3-4 minutes",
                            "season with salt and pepper, to taste. Stir in capers."],
               image: "https://s23209.pcdn.co/wp-content/uploads/2016/02/Easy-Lemon-Chicken-Piccata220602_DD_Easy-Lem-Chx-Piccata_397-1365x2048.jpg",
               servings: "4",
               cuisine: "Mediteranean",
               country: "France",
               notes: [],
               ingredients: [Ingredient(id: "1", quantity: 1, unit: "pound", name: "Spaghetti"),
                             Ingredient(id: "1", quantity: 1, unit: "pound", name: "boneless skinless chicken breasts, cut crosswise in half"),
                             Ingredient(id: "1", quantity: 0, unit: "", name: "Kosher salt and freshly ground black pepper, to taste"),
                             Ingredient(id: "1", quantity: 0.5, unit: "cup", name: "all-purpose flour"),
                             Ingredient(id: "1", quantity: 4, unit: "tablespoon", name: "unsalted butter, divided"),
                             Ingredient(id: "1", quantity: 2, unit: "clove", name: "garlic, minced"),
                             Ingredient(id: "1", quantity: 0.25, unit: "cup", name: "diced shallots"),
                             Ingredient(id: "1", quantity: 0.75, unit: "cup", name: "chicken broth"),
                             Ingredient(id: "1", quantity: 0.25, unit: "cup", name: "dry white wine"),
                             Ingredient(id: "1", quantity: 0, unit: "", name: "Juice of 1 lemon"),
                             Ingredient(id: "1", quantity: 0.5, unit: "cup", name: "heavy cream"),
                             Ingredient(id: "1", quantity: 0.25, unit: "cup", name: "capers, drained"),
                             Ingredient(id: "1", quantity: 2, unit: "tablespoon", name: "chopped fresh parsley leaves")],
               category: "Pasta",
               made: true,
               favorite: false),
        Recipe(id: "8", title: "Lemon  Chicken Piccata 2",
               description: "",
               link_to_original_web_page: "https://damndelicious.net/2016/02/26/easy-lemon-chicken-piccata/",
               author: "",
               time_in_seconds: 1800,
               directions: ["In a large pot of boiling salted water, cook pasta according to package instructions; drain well.",
                            "Season chicken with salt and pepper, to taste.",
                            "Working one at a time, dredge chicken in flour.",
                            "Melt 2 tablespoons butter in a large skillet over medium high heat. Add chicken and cook, flipping once, until cooked through, about 4-5 minutes on each side. Set aside and keep warm.",
                            "Melt remaining 2 tablespoons butter in the skillet. Add garlic and shallots, and cook, stirring frequently, until fragrant, about 2 minutes.",
                            "Stir in chicken broth, wine and lemon juice. Cook, stirring occasionally, until slightly reduced, about 5 minutes.",
                            "Gradually whisk in heavy cream until slightly thickened, about 3-4 minutes",
                            "season with salt and pepper, to taste. Stir in capers."],
               image: "https://s23209.pcdn.co/wp-content/uploads/2016/02/Easy-Lemon-Chicken-Piccata220602_DD_Easy-Lem-Chx-Piccata_397-1365x2048.jpg",
               servings: "4",
               cuisine: "Mediteranean",
               country: "France",
               notes: [],
               ingredients: [Ingredient(id: "1", quantity: 1, unit: "pound", name: "Spaghetti"),
                             Ingredient(id: "1", quantity: 1, unit: "pound", name: "boneless skinless chicken breasts, cut crosswise in half"),
                             Ingredient(id: "1", quantity: 0, unit: "", name: "Kosher salt and freshly ground black pepper, to taste"),
                             Ingredient(id: "1", quantity: 0.5, unit: "cup", name: "all-purpose flour"),
                             Ingredient(id: "1", quantity: 4, unit: "tablespoon", name: "unsalted butter, divided"),
                             Ingredient(id: "1", quantity: 2, unit: "clove", name: "garlic, minced"),
                             Ingredient(id: "1", quantity: 0.25, unit: "cup", name: "diced shallots"),
                             Ingredient(id: "1", quantity: 0.75, unit: "cup", name: "chicken broth"),
                             Ingredient(id: "1", quantity: 0.25, unit: "cup", name: "dry white wine"),
                             Ingredient(id: "1", quantity: 0, unit: "", name: "Juice of 1 lemon"),
                             Ingredient(id: "1", quantity: 0.5, unit: "cup", name: "heavy cream"),
                             Ingredient(id: "1", quantity: 0.25, unit: "cup", name: "capers, drained"),
                             Ingredient(id: "1", quantity: 2, unit: "tablespoon", name: "chopped fresh parsley leaves")],
               category: "Pasta",
               made: true,
               favorite: false),
        Recipe(id: "7", title: "Lemon  Chicken Piccata 3",
               description: "",
               link_to_original_web_page: "https://damndelicious.net/2016/02/26/easy-lemon-chicken-piccata/",
               author: "",
               time_in_seconds: 1800,
               directions: ["In a large pot of boiling salted water, cook pasta according to package instructions; drain well.",
                            "Season chicken with salt and pepper, to taste.",
                            "Working one at a time, dredge chicken in flour.",
                            "Melt 2 tablespoons butter in a large skillet over medium high heat. Add chicken and cook, flipping once, until cooked through, about 4-5 minutes on each side. Set aside and keep warm.",
                            "Melt remaining 2 tablespoons butter in the skillet. Add garlic and shallots, and cook, stirring frequently, until fragrant, about 2 minutes.",
                            "Stir in chicken broth, wine and lemon juice. Cook, stirring occasionally, until slightly reduced, about 5 minutes.",
                            "Gradually whisk in heavy cream until slightly thickened, about 3-4 minutes",
                            "season with salt and pepper, to taste. Stir in capers."],
               image: "https://s23209.pcdn.co/wp-content/uploads/2016/02/Easy-Lemon-Chicken-Piccata220602_DD_Easy-Lem-Chx-Piccata_397-1365x2048.jpg",
               servings: "4",
               cuisine: "Mediteranean",
               country: "France",
               notes: [],
               ingredients: [Ingredient(id: "1", quantity: 1, unit: "pound", name: "Spaghetti"),
                             Ingredient(id: "1", quantity: 1, unit: "pound", name: "boneless skinless chicken breasts, cut crosswise in half"),
                             Ingredient(id: "1", quantity: 0, unit: "", name: "Kosher salt and freshly ground black pepper, to taste"),
                             Ingredient(id: "1", quantity: 0.5, unit: "cup", name: "all-purpose flour"),
                             Ingredient(id: "1", quantity: 4, unit: "tablespoon", name: "unsalted butter, divided"),
                             Ingredient(id: "1", quantity: 2, unit: "clove", name: "garlic, minced"),
                             Ingredient(id: "1", quantity: 0.25, unit: "cup", name: "diced shallots"),
                             Ingredient(id: "1", quantity: 0.75, unit: "cup", name: "chicken broth"),
                             Ingredient(id: "1", quantity: 0.25, unit: "cup", name: "dry white wine"),
                             Ingredient(id: "1", quantity: 0, unit: "", name: "Juice of 1 lemon"),
                             Ingredient(id: "1", quantity: 0.5, unit: "cup", name: "heavy cream"),
                             Ingredient(id: "1", quantity: 0.25, unit: "cup", name: "capers, drained"),
                             Ingredient(id: "1", quantity: 2, unit: "tablespoon", name: "chopped fresh parsley leaves")],
               category: "Pasta",
               made: true,
               favorite: false),
        Recipe(id: "6", title: "Lemon  Chicken Piccata 1",
               description: "",
               link_to_original_web_page: "https://damndelicious.net/2016/02/26/easy-lemon-chicken-piccata/",
               author: "",
               time_in_seconds: 1800,
               directions: ["In a large pot of boiling salted water, cook pasta according to package instructions; drain well.",
                            "Season chicken with salt and pepper, to taste.",
                            "Working one at a time, dredge chicken in flour.",
                            "Melt 2 tablespoons butter in a large skillet over medium high heat. Add chicken and cook, flipping once, until cooked through, about 4-5 minutes on each side. Set aside and keep warm.",
                            "Melt remaining 2 tablespoons butter in the skillet. Add garlic and shallots, and cook, stirring frequently, until fragrant, about 2 minutes.",
                            "Stir in chicken broth, wine and lemon juice. Cook, stirring occasionally, until slightly reduced, about 5 minutes.",
                            "Gradually whisk in heavy cream until slightly thickened, about 3-4 minutes",
                            "season with salt and pepper, to taste. Stir in capers."],
               image: "https://s23209.pcdn.co/wp-content/uploads/2016/02/Easy-Lemon-Chicken-Piccata220602_DD_Easy-Lem-Chx-Piccata_397-1365x2048.jpg",
               servings: "4",
               cuisine: "Mediteranean",
               country: "France",
               notes: [],
               ingredients: [Ingredient(id: "1", quantity: 1, unit: "pound", name: "Spaghetti"),
                             Ingredient(id: "1", quantity: 1, unit: "pound", name: "boneless skinless chicken breasts, cut crosswise in half"),
                             Ingredient(id: "1", quantity: 0, unit: "", name: "Kosher salt and freshly ground black pepper, to taste"),
                             Ingredient(id: "1", quantity: 0.5, unit: "cup", name: "all-purpose flour"),
                             Ingredient(id: "1", quantity: 4, unit: "tablespoon", name: "unsalted butter, divided"),
                             Ingredient(id: "1", quantity: 2, unit: "clove", name: "garlic, minced"),
                             Ingredient(id: "1", quantity: 0.25, unit: "cup", name: "diced shallots"),
                             Ingredient(id: "1", quantity: 0.75, unit: "cup", name: "chicken broth"),
                             Ingredient(id: "1", quantity: 0.25, unit: "cup", name: "dry white wine"),
                             Ingredient(id: "1", quantity: 0, unit: "", name: "Juice of 1 lemon"),
                             Ingredient(id: "1", quantity: 0.5, unit: "cup", name: "heavy cream"),
                             Ingredient(id: "1", quantity: 0.25, unit: "cup", name: "capers, drained"),
                             Ingredient(id: "1", quantity: 2, unit: "tablespoon", name: "chopped fresh parsley leaves")],
               category: "Pasta",
               made: true,
               favorite: false),
        Recipe(id: "5", title: "Lemon  Chicken Piccata 2",
               description: "",
               link_to_original_web_page: "https://damndelicious.net/2016/02/26/easy-lemon-chicken-piccata/",
               author: "",
               time_in_seconds: 1800,
               directions: ["In a large pot of boiling salted water, cook pasta according to package instructions; drain well.",
                            "Season chicken with salt and pepper, to taste.",
                            "Working one at a time, dredge chicken in flour.",
                            "Melt 2 tablespoons butter in a large skillet over medium high heat. Add chicken and cook, flipping once, until cooked through, about 4-5 minutes on each side. Set aside and keep warm.",
                            "Melt remaining 2 tablespoons butter in the skillet. Add garlic and shallots, and cook, stirring frequently, until fragrant, about 2 minutes.",
                            "Stir in chicken broth, wine and lemon juice. Cook, stirring occasionally, until slightly reduced, about 5 minutes.",
                            "Gradually whisk in heavy cream until slightly thickened, about 3-4 minutes",
                            "season with salt and pepper, to taste. Stir in capers."],
               image: "https://s23209.pcdn.co/wp-content/uploads/2016/02/Easy-Lemon-Chicken-Piccata220602_DD_Easy-Lem-Chx-Piccata_397-1365x2048.jpg",
               servings: "4",
               cuisine: "Mediteranean",
               country: "France",
               notes: [],
               ingredients: [Ingredient(id: "1", quantity: 1, unit: "pound", name: "Spaghetti"),
                             Ingredient(id: "1", quantity: 1, unit: "pound", name: "boneless skinless chicken breasts, cut crosswise in half"),
                             Ingredient(id: "1", quantity: 0, unit: "", name: "Kosher salt and freshly ground black pepper, to taste"),
                             Ingredient(id: "1", quantity: 0.5, unit: "cup", name: "all-purpose flour"),
                             Ingredient(id: "1", quantity: 4, unit: "tablespoon", name: "unsalted butter, divided"),
                             Ingredient(id: "1", quantity: 2, unit: "clove", name: "garlic, minced"),
                             Ingredient(id: "1", quantity: 0.25, unit: "cup", name: "diced shallots"),
                             Ingredient(id: "1", quantity: 0.75, unit: "cup", name: "chicken broth"),
                             Ingredient(id: "1", quantity: 0.25, unit: "cup", name: "dry white wine"),
                             Ingredient(id: "1", quantity: 0, unit: "", name: "Juice of 1 lemon"),
                             Ingredient(id: "1", quantity: 0.5, unit: "cup", name: "heavy cream"),
                             Ingredient(id: "1", quantity: 0.25, unit: "cup", name: "capers, drained"),
                             Ingredient(id: "1", quantity: 2, unit: "tablespoon", name: "chopped fresh parsley leaves")],
               category: "Pasta",
               made: true,
               favorite: false),
        Recipe(id: "4", title: "Lemon  Chicken Piccata 3",
               description: "",
               link_to_original_web_page: "https://damndelicious.net/2016/02/26/easy-lemon-chicken-piccata/",
               author: "",
               time_in_seconds: 1800,
               directions: ["In a large pot of boiling salted water, cook pasta according to package instructions; drain well.",
                            "Season chicken with salt and pepper, to taste.",
                            "Working one at a time, dredge chicken in flour.",
                            "Melt 2 tablespoons butter in a large skillet over medium high heat. Add chicken and cook, flipping once, until cooked through, about 4-5 minutes on each side. Set aside and keep warm.",
                            "Melt remaining 2 tablespoons butter in the skillet. Add garlic and shallots, and cook, stirring frequently, until fragrant, about 2 minutes.",
                            "Stir in chicken broth, wine and lemon juice. Cook, stirring occasionally, until slightly reduced, about 5 minutes.",
                            "Gradually whisk in heavy cream until slightly thickened, about 3-4 minutes",
                            "season with salt and pepper, to taste. Stir in capers."],
               image: "https://s23209.pcdn.co/wp-content/uploads/2016/02/Easy-Lemon-Chicken-Piccata220602_DD_Easy-Lem-Chx-Piccata_397-1365x2048.jpg",
               servings: "4",
               cuisine: "Mediteranean",
               country: "France",
               notes: [],
               ingredients: [Ingredient(id: "1", quantity: 1, unit: "pound", name: "Spaghetti"),
                             Ingredient(id: "1", quantity: 1, unit: "pound", name: "boneless skinless chicken breasts, cut crosswise in half"),
                             Ingredient(id: "1", quantity: 0, unit: "", name: "Kosher salt and freshly ground black pepper, to taste"),
                             Ingredient(id: "1", quantity: 0.5, unit: "cup", name: "all-purpose flour"),
                             Ingredient(id: "1", quantity: 4, unit: "tablespoon", name: "unsalted butter, divided"),
                             Ingredient(id: "1", quantity: 2, unit: "clove", name: "garlic, minced"),
                             Ingredient(id: "1", quantity: 0.25, unit: "cup", name: "diced shallots"),
                             Ingredient(id: "1", quantity: 0.75, unit: "cup", name: "chicken broth"),
                             Ingredient(id: "1", quantity: 0.25, unit: "cup", name: "dry white wine"),
                             Ingredient(id: "1", quantity: 0, unit: "", name: "Juice of 1 lemon"),
                             Ingredient(id: "1", quantity: 0.5, unit: "cup", name: "heavy cream"),
                             Ingredient(id: "1", quantity: 0.25, unit: "cup", name: "capers, drained"),
                             Ingredient(id: "1", quantity: 2, unit: "tablespoon", name: "chopped fresh parsley leaves")],
               category: "Pasta",
               made: true,
               favorite: false),
        Recipe(id: "3", title: "Lemon  Chicken Piccata 1",
               description: "",
               link_to_original_web_page: "https://damndelicious.net/2016/02/26/easy-lemon-chicken-piccata/",
               author: "",
               time_in_seconds: 1800,
               directions: ["In a large pot of boiling salted water, cook pasta according to package instructions; drain well.",
                            "Season chicken with salt and pepper, to taste.",
                            "Working one at a time, dredge chicken in flour.",
                            "Melt 2 tablespoons butter in a large skillet over medium high heat. Add chicken and cook, flipping once, until cooked through, about 4-5 minutes on each side. Set aside and keep warm.",
                            "Melt remaining 2 tablespoons butter in the skillet. Add garlic and shallots, and cook, stirring frequently, until fragrant, about 2 minutes.",
                            "Stir in chicken broth, wine and lemon juice. Cook, stirring occasionally, until slightly reduced, about 5 minutes.",
                            "Gradually whisk in heavy cream until slightly thickened, about 3-4 minutes",
                            "season with salt and pepper, to taste. Stir in capers."],
               image: "https://s23209.pcdn.co/wp-content/uploads/2016/02/Easy-Lemon-Chicken-Piccata220602_DD_Easy-Lem-Chx-Piccata_397-1365x2048.jpg",
               servings: "4",
               cuisine: "Mediteranean",
               country: "France",
               notes: [],
               ingredients: [Ingredient(id: "1", quantity: 1, unit: "pound", name: "Spaghetti"),
                             Ingredient(id: "1", quantity: 1, unit: "pound", name: "boneless skinless chicken breasts, cut crosswise in half"),
                             Ingredient(id: "1", quantity: 0, unit: "", name: "Kosher salt and freshly ground black pepper, to taste"),
                             Ingredient(id: "1", quantity: 0.5, unit: "cup", name: "all-purpose flour"),
                             Ingredient(id: "1", quantity: 4, unit: "tablespoon", name: "unsalted butter, divided"),
                             Ingredient(id: "1", quantity: 2, unit: "clove", name: "garlic, minced"),
                             Ingredient(id: "1", quantity: 0.25, unit: "cup", name: "diced shallots"),
                             Ingredient(id: "1", quantity: 0.75, unit: "cup", name: "chicken broth"),
                             Ingredient(id: "1", quantity: 0.25, unit: "cup", name: "dry white wine"),
                             Ingredient(id: "1", quantity: 0, unit: "", name: "Juice of 1 lemon"),
                             Ingredient(id: "1", quantity: 0.5, unit: "cup", name: "heavy cream"),
                             Ingredient(id: "1", quantity: 0.25, unit: "cup", name: "capers, drained"),
                             Ingredient(id: "1", quantity: 2, unit: "tablespoon", name: "chopped fresh parsley leaves")],
               category: "Pasta",
               made: true,
               favorite: false),
        Recipe(id: "2", title: "Lemon  Chicken Piccata 2",
               description: "",
               link_to_original_web_page: "https://damndelicious.net/2016/02/26/easy-lemon-chicken-piccata/",
               author: "",
               time_in_seconds: 1800,
               directions: ["In a large pot of boiling salted water, cook pasta according to package instructions; drain well.",
                            "Season chicken with salt and pepper, to taste.",
                            "Working one at a time, dredge chicken in flour.",
                            "Melt 2 tablespoons butter in a large skillet over medium high heat. Add chicken and cook, flipping once, until cooked through, about 4-5 minutes on each side. Set aside and keep warm.",
                            "Melt remaining 2 tablespoons butter in the skillet. Add garlic and shallots, and cook, stirring frequently, until fragrant, about 2 minutes.",
                            "Stir in chicken broth, wine and lemon juice. Cook, stirring occasionally, until slightly reduced, about 5 minutes.",
                            "Gradually whisk in heavy cream until slightly thickened, about 3-4 minutes",
                            "season with salt and pepper, to taste. Stir in capers."],
               image: "https://s23209.pcdn.co/wp-content/uploads/2016/02/Easy-Lemon-Chicken-Piccata220602_DD_Easy-Lem-Chx-Piccata_397-1365x2048.jpg",
               servings: "4",
               cuisine: "Mediteranean",
               country: "France",
               notes: [],
               ingredients: [Ingredient(id: "1", quantity: 1, unit: "pound", name: "Spaghetti"),
                             Ingredient(id: "1", quantity: 1, unit: "pound", name: "boneless skinless chicken breasts, cut crosswise in half"),
                             Ingredient(id: "1", quantity: 0, unit: "", name: "Kosher salt and freshly ground black pepper, to taste"),
                             Ingredient(id: "1", quantity: 0.5, unit: "cup", name: "all-purpose flour"),
                             Ingredient(id: "1", quantity: 4, unit: "tablespoon", name: "unsalted butter, divided"),
                             Ingredient(id: "1", quantity: 2, unit: "clove", name: "garlic, minced"),
                             Ingredient(id: "1", quantity: 0.25, unit: "cup", name: "diced shallots"),
                             Ingredient(id: "1", quantity: 0.75, unit: "cup", name: "chicken broth"),
                             Ingredient(id: "1", quantity: 0.25, unit: "cup", name: "dry white wine"),
                             Ingredient(id: "1", quantity: 0, unit: "", name: "Juice of 1 lemon"),
                             Ingredient(id: "1", quantity: 0.5, unit: "cup", name: "heavy cream"),
                             Ingredient(id: "1", quantity: 0.25, unit: "cup", name: "capers, drained"),
                             Ingredient(id: "1", quantity: 2, unit: "tablespoon", name: "chopped fresh parsley leaves")],
               category: "Pasta",
               made: true,
               favorite: false),
        Recipe(id: "1", title: "Lemon  Chicken Piccata 3",
               description: "",
               link_to_original_web_page: "https://damndelicious.net/2016/02/26/easy-lemon-chicken-piccata/",
               author: "",
               time_in_seconds: 1800,
               directions: ["In a large pot of boiling salted water, cook pasta according to package instructions; drain well.",
                            "Season chicken with salt and pepper, to taste.",
                            "Working one at a time, dredge chicken in flour.",
                            "Melt 2 tablespoons butter in a large skillet over medium high heat. Add chicken and cook, flipping once, until cooked through, about 4-5 minutes on each side. Set aside and keep warm.",
                            "Melt remaining 2 tablespoons butter in the skillet. Add garlic and shallots, and cook, stirring frequently, until fragrant, about 2 minutes.",
                            "Stir in chicken broth, wine and lemon juice. Cook, stirring occasionally, until slightly reduced, about 5 minutes.",
                            "Gradually whisk in heavy cream until slightly thickened, about 3-4 minutes",
                            "season with salt and pepper, to taste. Stir in capers."],
               image: "https://s23209.pcdn.co/wp-content/uploads/2016/02/Easy-Lemon-Chicken-Piccata220602_DD_Easy-Lem-Chx-Piccata_397-1365x2048.jpg",
               servings: "4",
               cuisine: "Mediteranean",
               country: "France",
               notes: [],
               ingredients: [Ingredient(id: "1", quantity: 1, unit: "pound", name: "Spaghetti"),
                             Ingredient(id: "1", quantity: 1, unit: "pound", name: "boneless skinless chicken breasts, cut crosswise in half"),
                             Ingredient(id: "1", quantity: 0, unit: "", name: "Kosher salt and freshly ground black pepper, to taste"),
                             Ingredient(id: "1", quantity: 0.5, unit: "cup", name: "all-purpose flour"),
                             Ingredient(id: "1", quantity: 4, unit: "tablespoon", name: "unsalted butter, divided"),
                             Ingredient(id: "1", quantity: 2, unit: "clove", name: "garlic, minced"),
                             Ingredient(id: "1", quantity: 0.25, unit: "cup", name: "diced shallots"),
                             Ingredient(id: "1", quantity: 0.75, unit: "cup", name: "chicken broth"),
                             Ingredient(id: "1", quantity: 0.25, unit: "cup", name: "dry white wine"),
                             Ingredient(id: "1", quantity: 0, unit: "", name: "Juice of 1 lemon"),
                             Ingredient(id: "1", quantity: 0.5, unit: "cup", name: "heavy cream"),
                             Ingredient(id: "1", quantity: 0.25, unit: "cup", name: "capers, drained"),
                             Ingredient(id: "1", quantity: 2, unit: "tablespoon", name: "chopped fresh parsley leaves")],
               category: "Pasta",
               made: true,
               favorite: false)
    ]
}
