//
//  Recipe.swift
//  Chef Book
//
//  Created by David Grunsted on 6/21/24.
//

import Foundation
import SwiftData

//@Model
struct Recipe: Identifiable{
    let id: UUID
    var title: String
    var desc: String
    var link_to_original_web_page: String
    var author: String
    var time_in_seconds: Int
    var directions: [String]
    var images: [String]
    var servings: Int
    var cuisine: String
    var country: String
    var notes: [String]
    var ingredients: [Ingredient]
    var category: String
    var made: Bool
    var favorite: Bool
    
    init(id: UUID = UUID(), title: String, description: String, link_to_original_web_page: String, author: String, time_in_seconds: Int, directions: [String], images: [String], servings: Int, cuisine: String, country: String, notes: [String], ingredients: [Ingredient], category: String, made: Bool, favorite: Bool) {
        self.id = id
        self.title = title
        self.desc = description
        self.link_to_original_web_page = link_to_original_web_page
        self.author = author
        self.time_in_seconds = time_in_seconds
        self.directions = directions
        self.images = images
        self.servings = servings
        self.cuisine = cuisine
        self.country = country
        self.notes = notes
        self.ingredients = ingredients
        self.category = category
        self.made = made
        self.favorite = favorite
    }
}

extension Recipe {
    static var display_time: String {
        "2 hrs"
    }
}


extension Recipe {
    static let sampleData: [Recipe] =
    [
        Recipe(title: "Lemon  Chicken Piccata 1",
               description: "",
               link_to_original_web_page: "https://damndelicious.net/2016/02/26/easy-lemon-chicken-piccata/",
               author: "",
               time_in_seconds: 1800,
               directions: ["In a large pot of boiling salted water, cook pasta according to package instructions; drain well.",
                            "Season chicken with salt and pepper, to taste.",
                            "Working one at a time, dredge chicken in flour.",
                            "Melt 2 tablespoons butter in a large skillet over medium high heat. Add chicken and cook, flipping once, until cooked through, about 4-5 minutes on each side. Set aside and keep warm.",
                            "Melt remaining 2 tablespoons butter in the skillet. Add garlic and shallots, and cook, stirring frequently, until fragrant, about 2 minutes.",
                            "Stir in chicken broth, wine and lemon juice. Cook, stirring occasionally, until slightly reduced, about 5 minutes.",
                            "Gradually whisk in heavy cream until slightly thickened, about 3-4 minutes",
                            "season with salt and pepper, to taste. Stir in capers."],
               images: ["https://s23209.pcdn.co/wp-content/uploads/2016/02/Easy-Lemon-Chicken-Piccata220602_DD_Easy-Lem-Chx-Piccata_397-1365x2048.jpg"],
               servings: 4,
               cuisine: "Mediteranean",
               country: "France",
               notes: [],
               ingredients: [Ingredient(quantity: 1, unit: "pound", name: "Spaghetti"),
                             Ingredient(quantity: 1, unit: "pound", name: "boneless skinless chicken breasts, cut crosswise in half"),
                             Ingredient(quantity: 0, unit: "", name: "Kosher salt and freshly ground black pepper, to taste"),
                             Ingredient(quantity: 0.5, unit: "cup", name: "all-purpose flour"),
                             Ingredient(quantity: 4, unit: "tablespoon", name: "unsalted butter, divided"),
                             Ingredient(quantity: 2, unit: "clove", name: "garlic, minced"),
                             Ingredient(quantity: 0.25, unit: "cup", name: "diced shallots"),
                             Ingredient(quantity: 0.75, unit: "cup", name: "chicken broth"),
                             Ingredient(quantity: 0.25, unit: "cup", name: "dry white wine"),
                             Ingredient(quantity: 0, unit: "", name: "Juice of 1 lemon"),
                             Ingredient(quantity: 0.5, unit: "cup", name: "heavy cream"),
                             Ingredient(quantity: 0.25, unit: "cup", name: "capers, drained"),
                             Ingredient(quantity: 2, unit: "tablespoon", name: "chopped fresh parsley leaves")],
               category: "Pasta",
               made: true,
               favorite: false),
        Recipe(title: "Lemon  Chicken Piccata 2",
               description: "",
               link_to_original_web_page: "https://damndelicious.net/2016/02/26/easy-lemon-chicken-piccata/",
               author: "",
               time_in_seconds: 1800,
               directions: ["In a large pot of boiling salted water, cook pasta according to package instructions; drain well.",
                            "Season chicken with salt and pepper, to taste.",
                            "Working one at a time, dredge chicken in flour.",
                            "Melt 2 tablespoons butter in a large skillet over medium high heat. Add chicken and cook, flipping once, until cooked through, about 4-5 minutes on each side. Set aside and keep warm.",
                            "Melt remaining 2 tablespoons butter in the skillet. Add garlic and shallots, and cook, stirring frequently, until fragrant, about 2 minutes.",
                            "Stir in chicken broth, wine and lemon juice. Cook, stirring occasionally, until slightly reduced, about 5 minutes.",
                            "Gradually whisk in heavy cream until slightly thickened, about 3-4 minutes",
                            "season with salt and pepper, to taste. Stir in capers."],
               images: ["https://s23209.pcdn.co/wp-content/uploads/2016/02/Easy-Lemon-Chicken-Piccata220602_DD_Easy-Lem-Chx-Piccata_397-1365x2048.jpg"],
               servings: 4,
               cuisine: "Mediteranean",
               country: "France",
               notes: [],
               ingredients: [Ingredient(quantity: 1, unit: "pound", name: "Spaghetti"),
                             Ingredient(quantity: 1, unit: "pound", name: "boneless skinless chicken breasts, cut crosswise in half"),
                             Ingredient(quantity: 0, unit: "", name: "Kosher salt and freshly ground black pepper, to taste"),
                             Ingredient(quantity: 0.5, unit: "cup", name: "all-purpose flour"),
                             Ingredient(quantity: 4, unit: "tablespoon", name: "unsalted butter, divided"),
                             Ingredient(quantity: 2, unit: "clove", name: "garlic, minced"),
                             Ingredient(quantity: 0.25, unit: "cup", name: "diced shallots"),
                             Ingredient(quantity: 0.75, unit: "cup", name: "chicken broth"),
                             Ingredient(quantity: 0.25, unit: "cup", name: "dry white wine"),
                             Ingredient(quantity: 0, unit: "", name: "Juice of 1 lemon"),
                             Ingredient(quantity: 0.5, unit: "cup", name: "heavy cream"),
                             Ingredient(quantity: 0.25, unit: "cup", name: "capers, drained"),
                             Ingredient(quantity: 2, unit: "tablespoon", name: "chopped fresh parsley leaves")],
               category: "Pasta",
               made: true,
               favorite: false),
        Recipe(title: "Lemon  Chicken Piccata 3",
               description: "",
               link_to_original_web_page: "https://damndelicious.net/2016/02/26/easy-lemon-chicken-piccata/",
               author: "",
               time_in_seconds: 1800,
               directions: ["In a large pot of boiling salted water, cook pasta according to package instructions; drain well.",
                            "Season chicken with salt and pepper, to taste.",
                            "Working one at a time, dredge chicken in flour.",
                            "Melt 2 tablespoons butter in a large skillet over medium high heat. Add chicken and cook, flipping once, until cooked through, about 4-5 minutes on each side. Set aside and keep warm.",
                            "Melt remaining 2 tablespoons butter in the skillet. Add garlic and shallots, and cook, stirring frequently, until fragrant, about 2 minutes.",
                            "Stir in chicken broth, wine and lemon juice. Cook, stirring occasionally, until slightly reduced, about 5 minutes.",
                            "Gradually whisk in heavy cream until slightly thickened, about 3-4 minutes",
                            "season with salt and pepper, to taste. Stir in capers."],
               images: ["https://s23209.pcdn.co/wp-content/uploads/2016/02/Easy-Lemon-Chicken-Piccata220602_DD_Easy-Lem-Chx-Piccata_397-1365x2048.jpg"],
               servings: 4,
               cuisine: "Mediteranean",
               country: "France",
               notes: [],
               ingredients: [Ingredient(quantity: 1, unit: "pound", name: "Spaghetti"),
                             Ingredient(quantity: 1, unit: "pound", name: "boneless skinless chicken breasts, cut crosswise in half"),
                             Ingredient(quantity: 0, unit: "", name: "Kosher salt and freshly ground black pepper, to taste"),
                             Ingredient(quantity: 0.5, unit: "cup", name: "all-purpose flour"),
                             Ingredient(quantity: 4, unit: "tablespoon", name: "unsalted butter, divided"),
                             Ingredient(quantity: 2, unit: "clove", name: "garlic, minced"),
                             Ingredient(quantity: 0.25, unit: "cup", name: "diced shallots"),
                             Ingredient(quantity: 0.75, unit: "cup", name: "chicken broth"),
                             Ingredient(quantity: 0.25, unit: "cup", name: "dry white wine"),
                             Ingredient(quantity: 0, unit: "", name: "Juice of 1 lemon"),
                             Ingredient(quantity: 0.5, unit: "cup", name: "heavy cream"),
                             Ingredient(quantity: 0.25, unit: "cup", name: "capers, drained"),
                             Ingredient(quantity: 2, unit: "tablespoon", name: "chopped fresh parsley leaves")],
               category: "Pasta",
               made: true,
               favorite: false),
        Recipe(title: "Lemon  Chicken Piccata 1",
               description: "",
               link_to_original_web_page: "https://damndelicious.net/2016/02/26/easy-lemon-chicken-piccata/",
               author: "",
               time_in_seconds: 1800,
               directions: ["In a large pot of boiling salted water, cook pasta according to package instructions; drain well.",
                            "Season chicken with salt and pepper, to taste.",
                            "Working one at a time, dredge chicken in flour.",
                            "Melt 2 tablespoons butter in a large skillet over medium high heat. Add chicken and cook, flipping once, until cooked through, about 4-5 minutes on each side. Set aside and keep warm.",
                            "Melt remaining 2 tablespoons butter in the skillet. Add garlic and shallots, and cook, stirring frequently, until fragrant, about 2 minutes.",
                            "Stir in chicken broth, wine and lemon juice. Cook, stirring occasionally, until slightly reduced, about 5 minutes.",
                            "Gradually whisk in heavy cream until slightly thickened, about 3-4 minutes",
                            "season with salt and pepper, to taste. Stir in capers."],
               images: ["https://s23209.pcdn.co/wp-content/uploads/2016/02/Easy-Lemon-Chicken-Piccata220602_DD_Easy-Lem-Chx-Piccata_397-1365x2048.jpg"],
               servings: 4,
               cuisine: "Mediteranean",
               country: "France",
               notes: [],
               ingredients: [Ingredient(quantity: 1, unit: "pound", name: "Spaghetti"),
                             Ingredient(quantity: 1, unit: "pound", name: "boneless skinless chicken breasts, cut crosswise in half"),
                             Ingredient(quantity: 0, unit: "", name: "Kosher salt and freshly ground black pepper, to taste"),
                             Ingredient(quantity: 0.5, unit: "cup", name: "all-purpose flour"),
                             Ingredient(quantity: 4, unit: "tablespoon", name: "unsalted butter, divided"),
                             Ingredient(quantity: 2, unit: "clove", name: "garlic, minced"),
                             Ingredient(quantity: 0.25, unit: "cup", name: "diced shallots"),
                             Ingredient(quantity: 0.75, unit: "cup", name: "chicken broth"),
                             Ingredient(quantity: 0.25, unit: "cup", name: "dry white wine"),
                             Ingredient(quantity: 0, unit: "", name: "Juice of 1 lemon"),
                             Ingredient(quantity: 0.5, unit: "cup", name: "heavy cream"),
                             Ingredient(quantity: 0.25, unit: "cup", name: "capers, drained"),
                             Ingredient(quantity: 2, unit: "tablespoon", name: "chopped fresh parsley leaves")],
               category: "Pasta",
               made: true,
               favorite: false),
        Recipe(title: "Lemon  Chicken Piccata 2",
               description: "",
               link_to_original_web_page: "https://damndelicious.net/2016/02/26/easy-lemon-chicken-piccata/",
               author: "",
               time_in_seconds: 1800,
               directions: ["In a large pot of boiling salted water, cook pasta according to package instructions; drain well.",
                            "Season chicken with salt and pepper, to taste.",
                            "Working one at a time, dredge chicken in flour.",
                            "Melt 2 tablespoons butter in a large skillet over medium high heat. Add chicken and cook, flipping once, until cooked through, about 4-5 minutes on each side. Set aside and keep warm.",
                            "Melt remaining 2 tablespoons butter in the skillet. Add garlic and shallots, and cook, stirring frequently, until fragrant, about 2 minutes.",
                            "Stir in chicken broth, wine and lemon juice. Cook, stirring occasionally, until slightly reduced, about 5 minutes.",
                            "Gradually whisk in heavy cream until slightly thickened, about 3-4 minutes",
                            "season with salt and pepper, to taste. Stir in capers."],
               images: ["https://s23209.pcdn.co/wp-content/uploads/2016/02/Easy-Lemon-Chicken-Piccata220602_DD_Easy-Lem-Chx-Piccata_397-1365x2048.jpg"],
               servings: 4,
               cuisine: "Mediteranean",
               country: "France",
               notes: [],
               ingredients: [Ingredient(quantity: 1, unit: "pound", name: "Spaghetti"),
                             Ingredient(quantity: 1, unit: "pound", name: "boneless skinless chicken breasts, cut crosswise in half"),
                             Ingredient(quantity: 0, unit: "", name: "Kosher salt and freshly ground black pepper, to taste"),
                             Ingredient(quantity: 0.5, unit: "cup", name: "all-purpose flour"),
                             Ingredient(quantity: 4, unit: "tablespoon", name: "unsalted butter, divided"),
                             Ingredient(quantity: 2, unit: "clove", name: "garlic, minced"),
                             Ingredient(quantity: 0.25, unit: "cup", name: "diced shallots"),
                             Ingredient(quantity: 0.75, unit: "cup", name: "chicken broth"),
                             Ingredient(quantity: 0.25, unit: "cup", name: "dry white wine"),
                             Ingredient(quantity: 0, unit: "", name: "Juice of 1 lemon"),
                             Ingredient(quantity: 0.5, unit: "cup", name: "heavy cream"),
                             Ingredient(quantity: 0.25, unit: "cup", name: "capers, drained"),
                             Ingredient(quantity: 2, unit: "tablespoon", name: "chopped fresh parsley leaves")],
               category: "Pasta",
               made: true,
               favorite: false),
        Recipe(title: "Lemon  Chicken Piccata 3",
               description: "",
               link_to_original_web_page: "https://damndelicious.net/2016/02/26/easy-lemon-chicken-piccata/",
               author: "",
               time_in_seconds: 1800,
               directions: ["In a large pot of boiling salted water, cook pasta according to package instructions; drain well.",
                            "Season chicken with salt and pepper, to taste.",
                            "Working one at a time, dredge chicken in flour.",
                            "Melt 2 tablespoons butter in a large skillet over medium high heat. Add chicken and cook, flipping once, until cooked through, about 4-5 minutes on each side. Set aside and keep warm.",
                            "Melt remaining 2 tablespoons butter in the skillet. Add garlic and shallots, and cook, stirring frequently, until fragrant, about 2 minutes.",
                            "Stir in chicken broth, wine and lemon juice. Cook, stirring occasionally, until slightly reduced, about 5 minutes.",
                            "Gradually whisk in heavy cream until slightly thickened, about 3-4 minutes",
                            "season with salt and pepper, to taste. Stir in capers."],
               images: ["https://s23209.pcdn.co/wp-content/uploads/2016/02/Easy-Lemon-Chicken-Piccata220602_DD_Easy-Lem-Chx-Piccata_397-1365x2048.jpg"],
               servings: 4,
               cuisine: "Mediteranean",
               country: "France",
               notes: [],
               ingredients: [Ingredient(quantity: 1, unit: "pound", name: "Spaghetti"),
                             Ingredient(quantity: 1, unit: "pound", name: "boneless skinless chicken breasts, cut crosswise in half"),
                             Ingredient(quantity: 0, unit: "", name: "Kosher salt and freshly ground black pepper, to taste"),
                             Ingredient(quantity: 0.5, unit: "cup", name: "all-purpose flour"),
                             Ingredient(quantity: 4, unit: "tablespoon", name: "unsalted butter, divided"),
                             Ingredient(quantity: 2, unit: "clove", name: "garlic, minced"),
                             Ingredient(quantity: 0.25, unit: "cup", name: "diced shallots"),
                             Ingredient(quantity: 0.75, unit: "cup", name: "chicken broth"),
                             Ingredient(quantity: 0.25, unit: "cup", name: "dry white wine"),
                             Ingredient(quantity: 0, unit: "", name: "Juice of 1 lemon"),
                             Ingredient(quantity: 0.5, unit: "cup", name: "heavy cream"),
                             Ingredient(quantity: 0.25, unit: "cup", name: "capers, drained"),
                             Ingredient(quantity: 2, unit: "tablespoon", name: "chopped fresh parsley leaves")],
               category: "Pasta",
               made: true,
               favorite: false),
        Recipe(title: "Lemon  Chicken Piccata 1",
               description: "",
               link_to_original_web_page: "https://damndelicious.net/2016/02/26/easy-lemon-chicken-piccata/",
               author: "",
               time_in_seconds: 1800,
               directions: ["In a large pot of boiling salted water, cook pasta according to package instructions; drain well.",
                            "Season chicken with salt and pepper, to taste.",
                            "Working one at a time, dredge chicken in flour.",
                            "Melt 2 tablespoons butter in a large skillet over medium high heat. Add chicken and cook, flipping once, until cooked through, about 4-5 minutes on each side. Set aside and keep warm.",
                            "Melt remaining 2 tablespoons butter in the skillet. Add garlic and shallots, and cook, stirring frequently, until fragrant, about 2 minutes.",
                            "Stir in chicken broth, wine and lemon juice. Cook, stirring occasionally, until slightly reduced, about 5 minutes.",
                            "Gradually whisk in heavy cream until slightly thickened, about 3-4 minutes",
                            "season with salt and pepper, to taste. Stir in capers."],
               images: ["https://s23209.pcdn.co/wp-content/uploads/2016/02/Easy-Lemon-Chicken-Piccata220602_DD_Easy-Lem-Chx-Piccata_397-1365x2048.jpg"],
               servings: 4,
               cuisine: "Mediteranean",
               country: "France",
               notes: [],
               ingredients: [Ingredient(quantity: 1, unit: "pound", name: "Spaghetti"),
                             Ingredient(quantity: 1, unit: "pound", name: "boneless skinless chicken breasts, cut crosswise in half"),
                             Ingredient(quantity: 0, unit: "", name: "Kosher salt and freshly ground black pepper, to taste"),
                             Ingredient(quantity: 0.5, unit: "cup", name: "all-purpose flour"),
                             Ingredient(quantity: 4, unit: "tablespoon", name: "unsalted butter, divided"),
                             Ingredient(quantity: 2, unit: "clove", name: "garlic, minced"),
                             Ingredient(quantity: 0.25, unit: "cup", name: "diced shallots"),
                             Ingredient(quantity: 0.75, unit: "cup", name: "chicken broth"),
                             Ingredient(quantity: 0.25, unit: "cup", name: "dry white wine"),
                             Ingredient(quantity: 0, unit: "", name: "Juice of 1 lemon"),
                             Ingredient(quantity: 0.5, unit: "cup", name: "heavy cream"),
                             Ingredient(quantity: 0.25, unit: "cup", name: "capers, drained"),
                             Ingredient(quantity: 2, unit: "tablespoon", name: "chopped fresh parsley leaves")],
               category: "Pasta",
               made: true,
               favorite: false),
        Recipe(title: "Lemon  Chicken Piccata 2",
               description: "",
               link_to_original_web_page: "https://damndelicious.net/2016/02/26/easy-lemon-chicken-piccata/",
               author: "",
               time_in_seconds: 1800,
               directions: ["In a large pot of boiling salted water, cook pasta according to package instructions; drain well.",
                            "Season chicken with salt and pepper, to taste.",
                            "Working one at a time, dredge chicken in flour.",
                            "Melt 2 tablespoons butter in a large skillet over medium high heat. Add chicken and cook, flipping once, until cooked through, about 4-5 minutes on each side. Set aside and keep warm.",
                            "Melt remaining 2 tablespoons butter in the skillet. Add garlic and shallots, and cook, stirring frequently, until fragrant, about 2 minutes.",
                            "Stir in chicken broth, wine and lemon juice. Cook, stirring occasionally, until slightly reduced, about 5 minutes.",
                            "Gradually whisk in heavy cream until slightly thickened, about 3-4 minutes",
                            "season with salt and pepper, to taste. Stir in capers."],
               images: ["https://s23209.pcdn.co/wp-content/uploads/2016/02/Easy-Lemon-Chicken-Piccata220602_DD_Easy-Lem-Chx-Piccata_397-1365x2048.jpg"],
               servings: 4,
               cuisine: "Mediteranean",
               country: "France",
               notes: [],
               ingredients: [Ingredient(quantity: 1, unit: "pound", name: "Spaghetti"),
                             Ingredient(quantity: 1, unit: "pound", name: "boneless skinless chicken breasts, cut crosswise in half"),
                             Ingredient(quantity: 0, unit: "", name: "Kosher salt and freshly ground black pepper, to taste"),
                             Ingredient(quantity: 0.5, unit: "cup", name: "all-purpose flour"),
                             Ingredient(quantity: 4, unit: "tablespoon", name: "unsalted butter, divided"),
                             Ingredient(quantity: 2, unit: "clove", name: "garlic, minced"),
                             Ingredient(quantity: 0.25, unit: "cup", name: "diced shallots"),
                             Ingredient(quantity: 0.75, unit: "cup", name: "chicken broth"),
                             Ingredient(quantity: 0.25, unit: "cup", name: "dry white wine"),
                             Ingredient(quantity: 0, unit: "", name: "Juice of 1 lemon"),
                             Ingredient(quantity: 0.5, unit: "cup", name: "heavy cream"),
                             Ingredient(quantity: 0.25, unit: "cup", name: "capers, drained"),
                             Ingredient(quantity: 2, unit: "tablespoon", name: "chopped fresh parsley leaves")],
               category: "Pasta",
               made: true,
               favorite: false),
        Recipe(title: "Lemon  Chicken Piccata 3",
               description: "",
               link_to_original_web_page: "https://damndelicious.net/2016/02/26/easy-lemon-chicken-piccata/",
               author: "",
               time_in_seconds: 1800,
               directions: ["In a large pot of boiling salted water, cook pasta according to package instructions; drain well.",
                            "Season chicken with salt and pepper, to taste.",
                            "Working one at a time, dredge chicken in flour.",
                            "Melt 2 tablespoons butter in a large skillet over medium high heat. Add chicken and cook, flipping once, until cooked through, about 4-5 minutes on each side. Set aside and keep warm.",
                            "Melt remaining 2 tablespoons butter in the skillet. Add garlic and shallots, and cook, stirring frequently, until fragrant, about 2 minutes.",
                            "Stir in chicken broth, wine and lemon juice. Cook, stirring occasionally, until slightly reduced, about 5 minutes.",
                            "Gradually whisk in heavy cream until slightly thickened, about 3-4 minutes",
                            "season with salt and pepper, to taste. Stir in capers."],
               images: ["https://s23209.pcdn.co/wp-content/uploads/2016/02/Easy-Lemon-Chicken-Piccata220602_DD_Easy-Lem-Chx-Piccata_397-1365x2048.jpg"],
               servings: 4,
               cuisine: "Mediteranean",
               country: "France",
               notes: [],
               ingredients: [Ingredient(quantity: 1, unit: "pound", name: "Spaghetti"),
                             Ingredient(quantity: 1, unit: "pound", name: "boneless skinless chicken breasts, cut crosswise in half"),
                             Ingredient(quantity: 0, unit: "", name: "Kosher salt and freshly ground black pepper, to taste"),
                             Ingredient(quantity: 0.5, unit: "cup", name: "all-purpose flour"),
                             Ingredient(quantity: 4, unit: "tablespoon", name: "unsalted butter, divided"),
                             Ingredient(quantity: 2, unit: "clove", name: "garlic, minced"),
                             Ingredient(quantity: 0.25, unit: "cup", name: "diced shallots"),
                             Ingredient(quantity: 0.75, unit: "cup", name: "chicken broth"),
                             Ingredient(quantity: 0.25, unit: "cup", name: "dry white wine"),
                             Ingredient(quantity: 0, unit: "", name: "Juice of 1 lemon"),
                             Ingredient(quantity: 0.5, unit: "cup", name: "heavy cream"),
                             Ingredient(quantity: 0.25, unit: "cup", name: "capers, drained"),
                             Ingredient(quantity: 2, unit: "tablespoon", name: "chopped fresh parsley leaves")],
               category: "Pasta",
               made: true,
               favorite: false),
        Recipe(title: "Lemon  Chicken Piccata 1",
               description: "",
               link_to_original_web_page: "https://damndelicious.net/2016/02/26/easy-lemon-chicken-piccata/",
               author: "",
               time_in_seconds: 1800,
               directions: ["In a large pot of boiling salted water, cook pasta according to package instructions; drain well.",
                            "Season chicken with salt and pepper, to taste.",
                            "Working one at a time, dredge chicken in flour.",
                            "Melt 2 tablespoons butter in a large skillet over medium high heat. Add chicken and cook, flipping once, until cooked through, about 4-5 minutes on each side. Set aside and keep warm.",
                            "Melt remaining 2 tablespoons butter in the skillet. Add garlic and shallots, and cook, stirring frequently, until fragrant, about 2 minutes.",
                            "Stir in chicken broth, wine and lemon juice. Cook, stirring occasionally, until slightly reduced, about 5 minutes.",
                            "Gradually whisk in heavy cream until slightly thickened, about 3-4 minutes",
                            "season with salt and pepper, to taste. Stir in capers."],
               images: ["https://s23209.pcdn.co/wp-content/uploads/2016/02/Easy-Lemon-Chicken-Piccata220602_DD_Easy-Lem-Chx-Piccata_397-1365x2048.jpg"],
               servings: 4,
               cuisine: "Mediteranean",
               country: "France",
               notes: [],
               ingredients: [Ingredient(quantity: 1, unit: "pound", name: "Spaghetti"),
                             Ingredient(quantity: 1, unit: "pound", name: "boneless skinless chicken breasts, cut crosswise in half"),
                             Ingredient(quantity: 0, unit: "", name: "Kosher salt and freshly ground black pepper, to taste"),
                             Ingredient(quantity: 0.5, unit: "cup", name: "all-purpose flour"),
                             Ingredient(quantity: 4, unit: "tablespoon", name: "unsalted butter, divided"),
                             Ingredient(quantity: 2, unit: "clove", name: "garlic, minced"),
                             Ingredient(quantity: 0.25, unit: "cup", name: "diced shallots"),
                             Ingredient(quantity: 0.75, unit: "cup", name: "chicken broth"),
                             Ingredient(quantity: 0.25, unit: "cup", name: "dry white wine"),
                             Ingredient(quantity: 0, unit: "", name: "Juice of 1 lemon"),
                             Ingredient(quantity: 0.5, unit: "cup", name: "heavy cream"),
                             Ingredient(quantity: 0.25, unit: "cup", name: "capers, drained"),
                             Ingredient(quantity: 2, unit: "tablespoon", name: "chopped fresh parsley leaves")],
               category: "Pasta",
               made: true,
               favorite: false),
        Recipe(title: "Lemon  Chicken Piccata 2",
               description: "",
               link_to_original_web_page: "https://damndelicious.net/2016/02/26/easy-lemon-chicken-piccata/",
               author: "",
               time_in_seconds: 1800,
               directions: ["In a large pot of boiling salted water, cook pasta according to package instructions; drain well.",
                            "Season chicken with salt and pepper, to taste.",
                            "Working one at a time, dredge chicken in flour.",
                            "Melt 2 tablespoons butter in a large skillet over medium high heat. Add chicken and cook, flipping once, until cooked through, about 4-5 minutes on each side. Set aside and keep warm.",
                            "Melt remaining 2 tablespoons butter in the skillet. Add garlic and shallots, and cook, stirring frequently, until fragrant, about 2 minutes.",
                            "Stir in chicken broth, wine and lemon juice. Cook, stirring occasionally, until slightly reduced, about 5 minutes.",
                            "Gradually whisk in heavy cream until slightly thickened, about 3-4 minutes",
                            "season with salt and pepper, to taste. Stir in capers."],
               images: ["https://s23209.pcdn.co/wp-content/uploads/2016/02/Easy-Lemon-Chicken-Piccata220602_DD_Easy-Lem-Chx-Piccata_397-1365x2048.jpg"],
               servings: 4,
               cuisine: "Mediteranean",
               country: "France",
               notes: [],
               ingredients: [Ingredient(quantity: 1, unit: "pound", name: "Spaghetti"),
                             Ingredient(quantity: 1, unit: "pound", name: "boneless skinless chicken breasts, cut crosswise in half"),
                             Ingredient(quantity: 0, unit: "", name: "Kosher salt and freshly ground black pepper, to taste"),
                             Ingredient(quantity: 0.5, unit: "cup", name: "all-purpose flour"),
                             Ingredient(quantity: 4, unit: "tablespoon", name: "unsalted butter, divided"),
                             Ingredient(quantity: 2, unit: "clove", name: "garlic, minced"),
                             Ingredient(quantity: 0.25, unit: "cup", name: "diced shallots"),
                             Ingredient(quantity: 0.75, unit: "cup", name: "chicken broth"),
                             Ingredient(quantity: 0.25, unit: "cup", name: "dry white wine"),
                             Ingredient(quantity: 0, unit: "", name: "Juice of 1 lemon"),
                             Ingredient(quantity: 0.5, unit: "cup", name: "heavy cream"),
                             Ingredient(quantity: 0.25, unit: "cup", name: "capers, drained"),
                             Ingredient(quantity: 2, unit: "tablespoon", name: "chopped fresh parsley leaves")],
               category: "Pasta",
               made: true,
               favorite: false),
        Recipe(title: "Lemon  Chicken Piccata 3",
               description: "",
               link_to_original_web_page: "https://damndelicious.net/2016/02/26/easy-lemon-chicken-piccata/",
               author: "",
               time_in_seconds: 1800,
               directions: ["In a large pot of boiling salted water, cook pasta according to package instructions; drain well.",
                            "Season chicken with salt and pepper, to taste.",
                            "Working one at a time, dredge chicken in flour.",
                            "Melt 2 tablespoons butter in a large skillet over medium high heat. Add chicken and cook, flipping once, until cooked through, about 4-5 minutes on each side. Set aside and keep warm.",
                            "Melt remaining 2 tablespoons butter in the skillet. Add garlic and shallots, and cook, stirring frequently, until fragrant, about 2 minutes.",
                            "Stir in chicken broth, wine and lemon juice. Cook, stirring occasionally, until slightly reduced, about 5 minutes.",
                            "Gradually whisk in heavy cream until slightly thickened, about 3-4 minutes",
                            "season with salt and pepper, to taste. Stir in capers."],
               images: ["https://s23209.pcdn.co/wp-content/uploads/2016/02/Easy-Lemon-Chicken-Piccata220602_DD_Easy-Lem-Chx-Piccata_397-1365x2048.jpg"],
               servings: 4,
               cuisine: "Mediteranean",
               country: "France",
               notes: [],
               ingredients: [Ingredient(quantity: 1, unit: "pound", name: "Spaghetti"),
                             Ingredient(quantity: 1, unit: "pound", name: "boneless skinless chicken breasts, cut crosswise in half"),
                             Ingredient(quantity: 0, unit: "", name: "Kosher salt and freshly ground black pepper, to taste"),
                             Ingredient(quantity: 0.5, unit: "cup", name: "all-purpose flour"),
                             Ingredient(quantity: 4, unit: "tablespoon", name: "unsalted butter, divided"),
                             Ingredient(quantity: 2, unit: "clove", name: "garlic, minced"),
                             Ingredient(quantity: 0.25, unit: "cup", name: "diced shallots"),
                             Ingredient(quantity: 0.75, unit: "cup", name: "chicken broth"),
                             Ingredient(quantity: 0.25, unit: "cup", name: "dry white wine"),
                             Ingredient(quantity: 0, unit: "", name: "Juice of 1 lemon"),
                             Ingredient(quantity: 0.5, unit: "cup", name: "heavy cream"),
                             Ingredient(quantity: 0.25, unit: "cup", name: "capers, drained"),
                             Ingredient(quantity: 2, unit: "tablespoon", name: "chopped fresh parsley leaves")],
               category: "Pasta",
               made: true,
               favorite: false)
    ]
}
